[project]
name = "aws"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "amazon-dax-client>=2.0.6",
    "aws-sam-cli>=1.162.1",
    "boto3>=1.43.5",
    "cryptography>=48.0.1",
    "fastapi>=0.136.1",
    "git-remote-codecommit>=1.17",
    "joblib>=1.5.3",
    "learn>=1.0.0",
    "numpy>=2.4.4",
    "pandas>=3.0.2",
    "pydantic>=2.13.4",
    "pytest>=9.1.0",
    "python-jose[cryptography]>=3.5.0",
    "requests>=2.34.2",
    "sci-kit>=0.1.0",
    "scikit-learn>=1.8.0",
    "uvicorn>=0.46.0",
]
