AWSTemplateFormatVersion: '2010-09-09'
Description: 'Nested Tier 1: Isolation Networking Fabric'
Parameters:
  Environment:
    Type: String
Resources:
  DummyVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub 'ml-vpc-${Environment}'
Outputs:
  VpcId:
    Value: !Ref DummyVpc
